services:
  - type: web
    name: leech-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
